from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PUBLICATIONS_CSV = ROOT / "data" / "publications" / "publications.csv"
AWARDS_CSV = ROOT / "data" / "awards" / "awards.csv"
OUTPUT_JS = ROOT / "assets" / "site-data.js"

PUBLICATION_REQUIRED_FIELDS = [
    "id",
    "status",
    "articleType",
    "journalShort",
    "journalFull",
    "date",
    "title",
    "authors",
    "keywords",
    "abstract",
    "citation",
]

AWARD_REQUIRED_FIELDS = ["icon", "title", "detail", "issuer"]


def read_csv(path: Path, required_fields: list[str]) -> list[dict[str, str]]:
    if not path.exists():
        raise FileNotFoundError(f"Missing data file: {path}")

    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        if reader.fieldnames is None:
            raise ValueError(f"{path} has no header row")

        missing = [field for field in required_fields if field not in reader.fieldnames]
        if missing:
            raise ValueError(f"{path} is missing columns: {', '.join(missing)}")

        rows: list[dict[str, str]] = []
        for line_number, row in enumerate(reader, start=2):
            normalized = {field: (row.get(field) or "").strip() for field in required_fields}
            if not any(normalized.values()):
                continue
            if not normalized[required_fields[0]]:
                raise ValueError(f"{path}:{line_number} is missing '{required_fields[0]}'")
            rows.append(normalized)

    return rows


def read_publications() -> list[dict[str, str | int]]:
    publications = []
    seen_ids: set[int] = set()
    for row in read_csv(PUBLICATIONS_CSV, PUBLICATION_REQUIRED_FIELDS):
        try:
            pub_id = int(row["id"])
        except ValueError as exc:
            raise ValueError(f"{PUBLICATIONS_CSV}: publication id must be an integer: {row['id']}") from exc

        if pub_id in seen_ids:
            raise ValueError(f"{PUBLICATIONS_CSV}: duplicate publication id: {pub_id}")
        seen_ids.add(pub_id)

        publications.append({"id": pub_id, **{key: row[key] for key in PUBLICATION_REQUIRED_FIELDS if key != "id"}})

    return publications


def build_site_data() -> dict[str, object]:
    return {
        "publications": read_publications(),
        "awards": read_csv(AWARDS_CSV, AWARD_REQUIRED_FIELDS),
    }


def write_site_data(output_path: Path) -> None:
    data = build_site_data()
    serialized = json.dumps(data, ensure_ascii=False, indent=4)
    header = (
        "// This file is generated by scripts/build_site_data.py.\n"
        "// Edit CSV files under data/ and run update-site-data.ps1 instead.\n"
    )
    output_path.write_text(f"{header}window.siteData = {serialized};\n", encoding="utf-8")
    try:
        display_path = output_path.relative_to(ROOT)
    except ValueError:
        display_path = output_path
    print(f"Generated {display_path}")
    print(f"Publications: {len(data['publications'])}")
    print(f"Awards: {len(data['awards'])}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Build assets/site-data.js from CSV source data.")
    parser.add_argument("--output", type=Path, default=OUTPUT_JS, help="Output JS file path.")
    args = parser.parse_args()
    write_site_data(args.output if args.output.is_absolute() else ROOT / args.output)


if __name__ == "__main__":
    main()
